VERSIONING="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
AUTH_SERVER="https://api.stellar.org/auth"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GDVWPEOTJOPRT433PX6LULEPML5AN6QJO4GCFVFK43IPRQ23NPQAUSDF"]
[DOCUMENTATION]

ORG_NAME="Metaverse Studios"
ORG_URL="welcome-adh.pages.dev"
ORG_LOGO=""
ORG_DESCRIPTION="Fund Class/ LGR2. 






Private"
ORG_PHYSICAL_ADDRESS="1901 Avenue of the Stars., Los Angeles, CA 90067, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER=""
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE=""
ORG_TWITTER=""
ORG_GITHUB=""
ORG_OFFICIAL_EMAIL="metaversestudiosLA@protonmail.com"

[[PRINCIPALS]]

name="saas"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="MVRS"
issuer="GCFLUK4UK77337BRT6UGWP5UHYB73PSQ4HRACL6HJOQWH4GAKL4UX3RB"
display_decimals=4
name="Metaverse Studios"
desc="Fungible cryptocurrency"
conditions=""
image=""
fixed_number=""













