VERSIONING="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
AUTH_SERVER="https://api.stellar.org/auth"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GAKH6DXMK45TF7C6ZDJAFHARVRLW4GJIQHC64GX24IUBL4UJ3J7EFDRK"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GBL4VQ3DUMEQPC5I7WNWZQUZACEBRSUN4A474LX6YQC2PFUTDJ7YJHZA",
"GDYKGCJ55TSE6BTPGU2SFDIX73E56C2RQNC46BRQHG2KUCPQ55XOO5HR",
"GB7JR22TCIKGK6434ZBEZ3QQSUS5YLL7ALH7NIVRQQAW4RWJQBSXCJ4Q"
]
[DOCUMENTATION]

ORG_NAME="Metaverse Studios"
ORG_URL="welcome-adh.pages.dev"
ORG_LOGO=""
ORG_DESCRIPTION="Fund Class/ LGR2. 






Private"
ORG_PHYSICAL_ADDRESS="1901 Avenue of the Stars., Los Angeles, CA 90067, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER=""
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE=""
ORG_TWITTER=""
ORG_GITHUB=""
ORG_OFFICIAL_EMAIL="metaversestudiosLA@protonmail.com"

[[PRINCIPALS]]

name="saas"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="MVRS"
issuer="GAKH6DXMK45TF7C6ZDJAFHARVRLW4GJIQHC64GX24IUBL4UJ3J7EFDRK"
display_decimals=4
name="Metaverse Studios"
desc="Fungible cryptocurrency"
conditions=""
image=""
fixed_number=""













